/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './index.html',
        './App.tsx',
        './index.tsx',
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './contexts/**/*.{ts,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                surface: '#fcf8fa',
                'surface-dim': '#dcd9db',
                'surface-bright': '#fcf8fa',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f6f3f5',
                'surface-container': '#f0edef',
                'surface-container-high': '#eae7e9',
                'surface-container-highest': '#e4e2e4',
                'on-surface': '#1b1b1d',
                'on-surface-variant': '#45464d',
                'inverse-surface': '#303032',
                'inverse-on-surface': '#f3f0f2',
                outline: '#76777d',
                'outline-variant': '#c6c6cd',
                'surface-tint': '#565e74',
                primary: '#000000',
                'on-primary': '#ffffff',
                'primary-container': '#131b2e',
                'on-primary-container': '#7c839b',
                'inverse-primary': '#bec6e0',
                secondary: '#00687a',
                'on-secondary': '#ffffff',
                'secondary-container': '#57dffe',
                'on-secondary-container': '#006172',
                'secondary-fixed': '#acedff',
                'secondary-fixed-dim': '#4cd7f6',
                'brand-blue': '#3b82f6',
                'brand-cyan': '#06b6d4',
                'brand-magenta': '#d946ef',
                'brand-orange': '#f97316',
                'surface-dark': '#020617',
                'surface-card-dark': '#0f172a',
                'surface-container-dark': '#1e293b',
                'primary-fixed': '#dae2fd',
                'primary-fixed-dim': '#bec6e0',
                'tertiary-container': '#271901',
                'tertiary-fixed': '#fcdeb5',
                'tertiary-fixed-dim': '#dec29a',
            },
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
                mono: ['JetBrains Mono', 'monospace'],
                display: ['Inter', 'sans-serif'],
                label: ['JetBrains Mono', 'monospace'],
            },
        },
    },
    plugins: [],
};
